services:
  postgres:
    image: postgres:15-alpine
    container_name: smartshop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartshop_db
      POSTGRES_USER: smartshop
      POSTGRES_PASSWORD: securepassword123  # Use a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - smartshop_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartshop"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    image: smartshopbot:latest  # Replace with your actual image
    container_name: smartshop_bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - REDIS_URL=redis://redis:6379
      - AI_PROVIDER=${AI_PROVIDER}
      - ADMINER_PASSWORD=${ADMINER_PASSWORD}
    networks:
      - smartshop_network

networks:
  smartshop_network:
    driver: bridge

volumes:
  postgres_data: